spring:
  application:
    name: favorite
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cxp.shop_api.entity
  configuration:
    map-underscore-to-camel-case: true



ribbon:
  ConnectTimeout: 2000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
### Hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 5000




---
#开发环境
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cxpshop
    username: root
    password: 123456

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




---
#生产
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.101.147.15:3306/cxpshop
    username: root
    password: 123456

server:
  port: 7070

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 47.107.36.244
    non-secure-port: 7070
  client:
    service-url:
      defaultZone: http://47.101.147.15:8761/eureka

